export const icons = {
  eye: require('../images/eye.png'),
  'eye-closed': require('../images/eye-closed.png'),
  facebook: require('../images/facebook.png'),
  google: require('../images/google.png'),
  apple: require('../images/apple.png'),
  'message-icon': require('../images/message.png'),
  'arrow-left': require('../images/arrow-ios-left.png'),
  'arrow-right': require('../images/arrow-ios-right.png'),
  'avatar-2': require('../images/avatar-2.png'),
  'avatar-3': require('../images/avatar-3.png'),
  bell: require('../images/bell.png'),
  close: require('../images/close.png'),
  'company-page': require('../images/company-pag.png'),
  company: require('../images/company.png'),
  'credit-card': require('../images/credit-card.png'),
  list: require('../images/list.png'),
  'log-out': require('../images/log-out.png'),
  'more-horizontal': require('../images/more-horizontal.png'),
  search: require('../images/search.png'),
  settings: require('../images/settings.png'),
  continue: require('../images/continue.png'),
  'check-mark': require('../images/check-mark.png'),
  'arrow-ios-down': require('../images/arrow-ios-down.png'),
  'master-card': require('../images/master-card.png'),
  'success-icon': require('../images/success-icon.png'),
  'skills-plus': require('../images/skill-plus.png'),
  'check-mark-white': require('../images/check-mark-white.png'),
  people: require('../images/people.png'),
  book: require('../images/book.png'),
  qr: require('../images/qr.png'),
  'more-vertical': require('../images/more-vertical.png'),
  'phone-call': require('../images/phone-call.png'),
  'chevron-down': require('../images/chevron-down.png'),
  briefcase: require('../images/briefcase.png'),
  'person-outline': require('../images/person-outline.png'),
  'person-fill': require('../images/person-fill.png'),
  'eye-slash': require('../images/eye-slash.png'),
  lock: require('../images/lock.png'),
  or: require('../images/or.png'),
  sms: require('../images/sms.png'),
  'bg-image': require('../images/bg-image.png'),
  'home-buyer': require('../images/home-buyer.png'),
  contractor: require('../images/contractor.png'),
  'project-manager': require('../images/project-manager.png'),
  check: require('../images/check.png'),
  'user-new': require('../images/user-new.png'),
  pin: require('../images/pin.png'),
  'phone-plus': require('../images/phone-plus.png'),
  case: require('../images/case.png'),
  ein: require('../images/ein.png'),
  gallary: require('../images/gallary.png'),
  menu: require('../images/menu.png'),
  moon: require('../images/moon.png'),
  lock2: require('../images/lock2.png'),
  star: require('../images/star.png'),

  // work icons

  'work-1': require('../work/work-1.png'),
  'work-2': require('../work/work-2.png'),
  'work-3': require('../work/work-3.png'),
  'work-4': require('../work/work-4.png'),
  'work-5': require('../work/work-5.png'),
  'placeholder-image': require('../images/placeholder-image.png'),
  image: require('../images/image.png'),
};

export type IconTypes = keyof typeof icons;
